version: "3.7"

services:
  dapr_placement_dc:
    container_name: dapr_placement_dc
    image: "daprio/dapr"
    command: [ "./placement", "--port", "50006" ]
    ports:
      - "50006:50006"
    networks:
      - hello-dapr

  dapr_zipkin_dc:
    container_name: dapr_zipkin_dc
    image: "openzipkin/zipkin:latest"
    ports:
      - "9411:9411"
    networks:
      - hello-dapr

  dapr_consul_dc:
    container_name: dapr_consul_dc
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
    networks:
      - hello-dapr

  ##### Greeting Service & DAPR Sidecar #####
  greeting_service:
    container_name: greeting_service
    build:
      context: ./demo-greeting
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - dapr_placement_dc
      - dapr_consul_dc
      - dapr_zipkin_dc
    networks:
      - hello-dapr

  greeting_dapr:
    container_name: greeting_dapr
    image: "daprio/daprd:edge"
    command:
      [
        "./daprd",
        "-app-id", "greeting",
        "--dapr-http-port", "4001",
        "-app-port", "3001",
        "-config", "/dapr-config/consul-zipkin-config.yaml",
      ]
    volumes:
      - "./dapr-config/:/dapr-config"
    depends_on:
      - greeting_service
      - dapr_placement_dc
      - dapr_consul_dc
      - dapr_zipkin_dc
    network_mode: "service:greeting_service"

  ##### Gateway service & DAPR Sidecar #####
  gateway_service:
    container_name: gateway_service
    build:
      context: ./demo-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - dapr_placement_dc
      - dapr_consul_dc
      - dapr_zipkin_dc
    networks:
      - hello-dapr

  gateway_dapr:
    container_name: gateway_dapr
    image: "daprio/daprd:edge"
    command:
      [
        "./daprd",
        "-app-id",  "gateway",
        "--dapr-http-port", "4000",
        "-app-port", "3000",
        "-config", "/dapr-config/consul-zipkin-config.yaml",
      ]
    volumes:
      - "./dapr-config/:/dapr-config"
    depends_on:
      - gateway_service
      - dapr_placement_dc
      - dapr_consul_dc
      - dapr_zipkin_dc
    network_mode: "service:gateway_service"

networks:
  hello-dapr:
