apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  nameResolution:
    component: "consul"
    configuration:
      selfRegister: true
      client:
        address: "host.docker.internal:8500"
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://host.docker.internal:9411/api/v2/spans"
